general {
  inhibit_sleep = 3
  before_sleep_cmd = hyprlock
}
listener {
  timeout = 300
  on-timeout = hyprlock
}

listener {
  timeout = 1800
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'

}

listener {
  timeout = 3600
  on-timeout = systemctl suspend
}
