$discord = flatpak run com.discordapp.Discord
$gmusic = /opt/google/chrome/google-chrome --profile-directory=Default --app-id=cinhimbnkkaeohfgghhklpknlkffjgod

exec-once = [workspace main silent] $terminal & $browser 
exec-once = [workspace chat silent] $discord & $gmusic

